version: "3"
services:
  shadows-db:
    user: "0:989"
    container_name: strapi-shadows-db
    build: .
    image: mystrapi:latest
    restart: unless-stopped
    env_file: .env
    # must create shadows-network if it doesnt exist
    network_mode: shadows-network
    environment:
     # DATABASE_CLIENT: ${DATABASE_CLIENT}
     # DATABASE_HOST: strapiDB
     # DATABASE_NAME: ${DATABASE_NAME}
     # DATABASE_USERNAME: ${DATABASE_USERNAME}
     # DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
     # DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials
      - ./config:/opt/app/config
      - ./data.db:/opt/app/.tmp/data.db
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
      - ./.env:/opt/app/.env
    ports:
      - "127.0.0.1:1337:1337"
